s3_parquet_location:
    path: "s3a://test.txt"
    s3readpath: "s3a://qdbxcntrltrst-stg/brndd_card_datadl/httk_csv/test_parquet/sample.parquet/"
    s3path: "s3a://qdbxcntrltrst-stg/brndd_card_datadl/httk_csv/test_parquet/sample.parquet"

s3_get_parquet_loc:
   s3_file_one: "s3a://qdbxcntrltrst-stg/brndd_card_datadl/httk_csv/test_parquet/part-r-00000-39ff8dd7-6b2f-4b85-95d0-734526c14c81.snappy.parquet"
   s3_file_two: "s3a://qdbxcntrltrst-stg/brndd_card_datadl/httk_csv/test_parquet/part-r-00000-800ff65d-6489-4bd9-9480-350855d6be03.snappy.parquet"

par_hdfs_s3:
    s3_file_dir: "s3a://qdbxcntrltrst-stg/brndd_card_datadl/httk_csv/test_parquet/"

card_evt_type:
        path: "/user/tws626/par_f/card_table_1.parquet"
card_sys_evt:
        path: "/user/tws626/card_table_2.parquet"